name: TEST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Start server
        run: pnpm run start &
        env:
          NODE_ENV: production

      - name: Wait for server to start
        run: npx wait-on http://localhost:5173

      - name: Run tests
        run: pnpm test
